import { Inter } from "next/font/google";
import "./globals.css";

import Footer from "@/components/footer/page";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BOPTII FITS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        {children}
      </body>
      <Footer />
    </html>
  );
}
